services:
  app:
    container_name: app
    restart: unless-stopped
    build:
      context: ..
      dockerfile: deployments/Dockerfile
    env_file: ../.env
    ports:
      - "52883:52883"
      - "3000:3000"
    cap_add:
      - ALL
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - "../data:/wireguard_server/data"
